myprop:
  username: Prod Env

logging:
  level:
    com:
      miniproject:
        joongo: info

spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/rookiejangter_db
    username: rookiejangter
    password: rookiejangter
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none # <-- JPA의 DDL 자동 생성 비활성화 (Flyway가 DDL을 관리)
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        default_schema: rookiejangter_db
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: never # <-- 스프링 부트의 내장 SQL 초기화 기능 비활성화
  flyway:
    locations: classpath:db/migration # 마이그레이션 스크립트가 위치할 경로
    enabled: true # Flyway 활성화
    baseline-on-migrate: true # 기존 DB에 테이블이 있을 경우 Flyway가 현재 상태를 기준으로 베이스라인을 설정
#    clean-disabled: false  # 프로덕션 환경에서는 비활성화 권장
#    schemas: rookiejangter_db # 특정 스키마에서 작업할 경우 (선택 사항, default-schema와 유사)